train_path: data/tokenized/tinystories_train.npy
eval_path: data/tokenized/tinystories_valid.npy
checkpoint_dir: cs336_basics/scripts/train/checkpoints/
checkpoint_every: 5
epochs: 1
eval_every: 5
shuffle: True

rope:
  theta: 0.7853981633974483 # pi/4

transformer:
  d_model: 16
  num_heads: 2
  context_length: 4
  num_layers: 2
  d_ff: 32

tokenizer:
  checkpoint_dir: cs336_basics/tokenizer/checkpoints/tinystories/
  special_tokens: ["<|endoftext|>"]

optimizer:
  lr: 1e-1
  weight_decay: 1e-2
  betas: [0.9, 0.999]
